- name: Install the ansible-pull script
  become: true
  ansible.builtin.copy: src=ansible-pull.sh remote_src=true dest=/usr/sbin/run-ansible-pull mode=0755 owner=root group=root

- name: Install cronjob
  ansible.builtin.cron: name="Ansible Pull" minute="{{ ansible_local.pull.minute | default(59 | random) }}" job="/usr/sbin/run-ansible-pull"

